CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  username TEXT,
  about TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  usercl TEXT
);

CREATE TABLE IF NOT EXISTS posts9 (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title TEXT,
  content TEXT,
  user_id INT REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE IF NOT EXISTS replies9 (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title TEXT,
  content TEXT,
  post_id INT REFERENCES posts9(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE IF NOT EXISTS tags9 (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  tag TEXT
);

CREATE TABLE IF NOT EXISTS posts9_tags9(
  post_id INTEGER REFERENCES posts9(id),
  tag_id INTEGER REFERENCES tags9(id),
  PRIMARY KEY (post_id,tag_id)
);

CREATE TABLE IF NOT EXISTS follows(
  user_id INTEGER REFERENCES users(id),
  follows_id INTEGER REFERENCES users(id),
  PRIMARY KEY (user_id, follows_id)
);

CREATE TABLE IF NOT EXISTS likes(
  user_id INTEGER REFERENCES users(id),
  post_id INTEGER REFERENCES posts9(id),
  PRIMARY KEY (user_id,post_id)
);